### ISSUE TITLE
Bug: isCancelable True and Rotate Device

### ISSUE THREAD

**Issue by webserveis** [Lars3n95/AppRater-Dialog#14]
I test function isCancelable() and posible escenarios

When dialog is show and rotate device recive error 

> E/WindowManager: android.view.WindowLeaked
> line: com.kila.apprater_dialog.lars.AppRater$DefaultBuilder.showAppRaterDialog(AppRater.java:123)
 

**Posible solutions:**
http://stackoverflow.com/questions/32065854/activity-has-leaked-window-at-alertdialog-show-method

Maybe construct dialog over `DialogFragment` several things are solved:

If dialog is show and isCancelable(true) when rotate device dialog will continue to be shown

**Comment by Lars3n95** [comment]
Can't reproduce
