### ISSUE TITLE
Bug! Don't work fine market://...

### ISSUE THREAD

**Issue by webserveis** [Lars3n95/AppRater-Dialog#17]
I use 1.2.0

`new AppRater.DefaultBuilder(this, "my.id.app")`

when push Rate, go to palystore but error

Element no found, retry

I see you construct
market://details?id=my.id.app

If you change for, work perferly
https://play.google.com/store/apps/details?id=my.id.app

[I found this for maintanence market://](https://stackoverflow.com/questions/11753000/how-to-open-the-google-play-store-directly-from-my-android-application)

**Comment by Lars3n95** [comment]
Thanks, should be fixed with 1.2.1.
