### ISSUE TITLE
This dialog will update reviews on Store?

### ISSUE THREAD

**Issue by PaolinoAngeletti** [Lars3n95/AppRater-Dialog#18]
This isnt't clear: 
this library will update automatically the reviews on Store ?
Or i have to implement something else ?
In that case, What is the code for update reviews on Store ?
Thanks

**Comment by Lars3n95** [comment]
Hello,

as far as I know it is not possible to change the ratings in the store from external. This library just redirects to the store, so that the user can rate the app (hoping that he gives the same number he did in this library).
